### PR TITLE
Support moodle 4.5

### PR DESCRIPTION
**Pull request by tuanngocnguyen**

### CODE REVIEW

**Comment by danmarsden** [comment]
If we're going to move from print_error to an exception, we should probably put the lang string into the lang file at the same time instead of hard-coding the string.

**Comment by danmarsden** [comment]
spotted the failures in the older brnaches when running behat so I just pushed a new 4.1 stable branch but that means the version conflicts here now sorry! - hopefully a quick rebase (and fixing that hard-coded lang strign in the exception) and this can be merged in.

**Comment by tuanngocnguyen** [comment]
Thanks @danmarsden ,

I have re-based and fixed hard-coded string.

**Comment by tuanngocnguyen** [comment]
actually, let me rename the string error_upgrade_script

**Comment by tuanngocnguyen** [comment]
Hi @danmarsden ,

Would you please have another review once you have some time?
Thanks

**Comment by danmarsden** [comment]
thanks - just the incorrect $plugin->release value in the version.php - it should ideally match the version number - once you fix that just merge it in!

**Comment by tuanngocnguyen** [comment]
Thanks @danmarsden ,

I have fixed the release number.

**Pull request merged**
